AWSTemplateFormatVersion: "2010-09-09"
Description: This template builds the necessary lambda infra to send cloudwatch logs to honeycomb
Parameters:
  Environment:
    Type: String
    Default: ''
    Description: Name of environment, if applicable
  HoneycombWriteKey:
    Type: String
    Description: KMS-encrypted blob of your honeycomb write key
  KMSKeyId:
    Type: String
    Description: Id of KMS key used to encrypt the Honeycomb Write Key in SSM
  HoneycombAPIHost:
    Type: String
    Default: https://api.honeycomb.io
    Description: Optionally set an alternative API host
  HoneycombDataset:
    Type: String
    Default: honeycomb-cloudwatch-logs
    Description: Target honeycomb dataset
  HoneycombSampleRate:
    Type: Number
    Default: 1
    Description: Sample rate
  LogGroupName:
    Type: String
    Description: The name of the AWS cloudwatch log group you want to subscribe to
  FilterPattern:
    Type: String
    Default: ''
    Description: The filtering expressions that restrict which cloudwatch log lines get sent
  TimeFieldName:
    Type: String
    Default: ''
    Description: Name of the field that contains a timestamp
  TimeFieldFormat:
    Type: String
    Default: ''
    Description: Timestamp format to use (strftime and Golang time.Parse supported)
  HandlerVersion:
    Type: String
    Default: 'LATEST'
    Description: Optional desired version of the cloudwatch handler to use.
Resources:
  CloudwatchLambdaHandler:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: honeycomb-builds
        S3Key:
          "Fn::Join":
            - ''
            -
              - honeycombio/serverless-ingest-poc/ingest-handlers-
              - !Ref HandlerVersion
              - .zip
      Description: Lambda function for sending cloudwatch logs to Honeycomb
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PARSER_TYPE: json
          HONEYCOMB_WRITE_KEY: !Ref HoneycombWriteKey
          API_HOST: !Ref HoneycombAPIHost
          DATASET: !Ref HoneycombDataset
          SAMPLE_RATE: !Ref HoneycombSampleRate
          TIME_FIELD_NAME: !Ref TimeFieldName
          TIME_FIELD_FORMAT: !Ref TimeFieldFormat
      FunctionName:
        "Fn::Join":
          - '-'
          -
            - CloudwatchLambdaHandler
            - !Ref "AWS::StackName"
      Handler: cloudwatch-handler
      MemorySize: 128
      Role:
        "Fn::GetAtt":
          - LambdaIAMRole
          - Arn
      Runtime: go1.x
      Timeout: 10
  ExecutePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      Principal: 'logs.amazonaws.com'
  CloudwatchSubscriptionFilter:
    Type: "AWS::Logs::SubscriptionFilter"
    Properties:
      DestinationArn:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      LogGroupName: !Ref LogGroupName
      FilterPattern: !Ref FilterPattern
    DependsOn: ExecutePermission
  LambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  LambdaRolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "foo"
      Roles:
          - Ref: LambdaIAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:*:*:*'
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource:
              "Fn::Join":
                - ''
                -
                  - arn:aws:kms:*:*:key/
                  - !Ref KMSKeyId
